// packages/react/src/components/radio-group/radio-group.tsx
import { Radio as RadioBase } from "@base-ui/react/radio";
import { RadioGroup as RadioGroupBase } from "@base-ui/react/radio-group";
import * as styles from "@openlab-ui/core/radio-group/radio-group.css";

export function RadioGroup(props: RadioGroupBase.Props) {
  return (
    <RadioGroupBase
      data-slot="radio-group"
      className={styles.root}
      {...props}
    />
  );
}

export function RadioGroupItem(props: RadioBase.Root.Props) {
  return (
    <RadioBase.Root
      data-slot="radio-group-item"
      className={styles.item}
      {...props}
    >
      <RadioBase.Indicator
        data-slot="radio-group-indicator"
        className={styles.indicator}
      >
        <span className={styles.indicatorDot} />
      </RadioBase.Indicator>
    </RadioBase.Root>
  );
}

// packages/vue/src/components/radio-group/RadioGroup.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/radio-group/radio-group.css";
import { provide, ref } from "vue";

interface Props {
  modelValue?: string;
  defaultValue?: string;
  name?: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{ "update:modelValue": [value: string] }>();

const selected = ref(props.modelValue ?? props.defaultValue ?? "");

provide("radio-group", {
  name: props.name,
  selected,
  select: (value: string) => {
    selected.value = value;
    emit("update:modelValue", value);
  },
});
</script>

<template>
  <div data-slot="radio-group" role="radiogroup" :class="styles.root">
    <slot />
  </div>
</template>
