// examples/docs/src/components/previews/react/SwitchPreview.tsx
import { Switch, Label, Field } from "@openlab-ui/react";
import { ReactPreviewProvider } from "../../ReactPreviewProvider";

export function SwitchBasic() {
  return (
    <ReactPreviewProvider>
      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
        <Field orientation="horizontal">
          <Switch id="notifications" defaultChecked />
          <Label htmlFor="notifications">Enable notifications</Label>
        </Field>
        <Field orientation="horizontal">
          <Switch id="emails" />
          <Label htmlFor="emails">Marketing emails</Label>
        </Field>
        <Field orientation="horizontal">
          <Switch id="sw-disabled" disabled />
          <Label htmlFor="sw-disabled">Disabled</Label>
        </Field>
      </div>
    </ReactPreviewProvider>
  );
}

// examples/docs/src/components/previews/vue/SwitchPreview.vue
<script setup lang="ts">
import { Switch, Label, Field } from "@openlab-ui/vue";
import VuePreviewProvider from "../../VuePreviewProvider.vue";
</script>

<template>
  <VuePreviewProvider>
    <div style="display: flex; flex-direction: column; gap: 0.75rem">
      <Field orientation="horizontal">
        <Switch id="notifications-vue" :default-checked="true" />
        <Label for="notifications-vue">Enable notifications</Label>
      </Field>
      <Field orientation="horizontal">
        <Switch id="emails-vue" />
        <Label for="emails-vue">Marketing emails</Label>
      </Field>
      <Field orientation="horizontal">
        <Switch id="sw-disabled-vue" :disabled="true" />
        <Label for="sw-disabled-vue">Disabled</Label>
      </Field>
    </div>
  </VuePreviewProvider>
</template>
