// packages/vue/src/components/switch/Switch.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/switch/switch.css";
import { computed } from "vue";

interface Props {
  size?: "default" | "sm";
  disabled?: boolean;
  defaultChecked?: boolean;
}

const props = withDefaults(defineProps<Props>(), { size: "default" });

const model = defineModel<boolean>({ default: false });

const isChecked = computed(() => model.value ?? props.defaultChecked ?? false);
</script>

<template>
  <button
    type="button"
    role="switch"
    data-slot="switch"
    :data-size="props.size"
    :aria-checked="isChecked"
    :data-checked="isChecked ? '' : undefined"
    :data-unchecked="!isChecked ? '' : undefined"
    :disabled="props.disabled"
    :class="styles.root"
    @click="model = !isChecked"
  >
    <span data-slot="switch-thumb" :class="styles.thumb" />
  </button>
</template>

// packages/react/src/components/switch/switch.tsx
import { Switch as SwitchBase } from "@base-ui/react/switch";
import * as styles from "@openlab-ui/core/switch/switch.css";

export type SwitchProps = SwitchBase.Root.Props & { size?: "default" | "sm" };

export function Switch({ size = "default", ...props }: SwitchProps) {
  return (
    <SwitchBase.Root
      data-slot="switch"
      data-size={size}
      className={styles.root}
      {...props}
    >
      <SwitchBase.Thumb data-slot="switch-thumb" className={styles.thumb} />
    </SwitchBase.Root>
  );
}
Switch.displayName = "OpenLabUISwitch";
