// packages/react/src/components/datatable/datatable.tsx
import {
  type ColumnDef,
  flexRender,
  getCoreRowModel,
  useReactTable,
} from "@tanstack/react-table";
import * as styles from "@openlab-ui/core/datatable/datatable.css";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../table/table";

interface DataTableProps<TData, TValue> {
  columns: ColumnDef<TData, TValue>[];
  data: TData[];
}

export function DataTable<TData, TValue>({
  columns,
  data,
}: DataTableProps<TData, TValue>) {
  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <div className={styles.datatableWrapper}>
      <Table>
        <TableHeader>
          {table.getHeaderGroups().map((headerGroup) => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map((header) => (
                <TableHead key={header.id}>
                  {header.isPlaceholder
                    ? null
                    : flexRender(
                        header.column.columnDef.header,
                        header.getContext(),
                      )}
                </TableHead>
              ))}
            </TableRow>
          ))}
        </TableHeader>
        <TableBody>
          {table.getRowModel().rows?.length ? (
            table.getRowModel().rows.map((row) => (
              <TableRow
                key={row.id}
                data-state={row.getIsSelected() && "selected"}
              >
                {row.getVisibleCells().map((cell) => (
                  <TableCell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </TableCell>
                ))}
              </TableRow>
            ))
          ) : (
            <TableRow>
              <TableCell colSpan={columns.length} className={styles.emptyCell}>
                No results.
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </div>
  );
}

// packages/vue/src/components/datatable/DataTable.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/datatable/datatable.css";
import * as tableStyles from "@openlab-ui/core/table/table.css";

interface Column<T> {
  key: keyof T;
  header: string;
  cell?: (row: T) => string;
}

interface Props<T = Record<string, unknown>> {
  columns: Column<T>[];
  data: T[];
  emptyText?: string;
}

const props = withDefaults(defineProps<Props>(), { emptyText: "No results." });
</script>

<template>
  <div :class="styles.datatableWrapper">
    <div :class="tableStyles.tableContainer">
      <table :class="tableStyles.table">
        <thead :class="tableStyles.thead">
          <tr :class="tableStyles.tr">
            <th
              v-for="col in props.columns"
              :key="String(col.key)"
              :class="tableStyles.th"
            >
              {{ col.header }}
            </th>
          </tr>
        </thead>
        <tbody :class="tableStyles.tbody">
          <template v-if="props.data.length">
            <tr
              v-for="(row, i) in props.data"
              :key="i"
              :class="tableStyles.tr"
            >
              <td
                v-for="col in props.columns"
                :key="String(col.key)"
                :class="tableStyles.td"
              >
                {{ col.cell ? col.cell(row) : row[col.key] }}
              </td>
            </tr>
          </template>
          <tr v-else :class="tableStyles.tr">
            <td
              :colspan="props.columns.length"
              :class="[tableStyles.td, styles.emptyCell]"
            >
              {{ props.emptyText }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
