// packages/vue/src/components/toggle-group/ToggleGroup.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/toggle-group/toggle-group.css";
import { provide } from "vue";

interface Props {
  variant?: "default" | "outline";
  size?: "default" | "sm" | "lg";
  spacing?: number;
  orientation?: "horizontal" | "vertical";
  type?: "single" | "multiple";
  defaultValue?: string | string[];
}

const props = withDefaults(defineProps<Props>(), {
  variant: "default",
  size: "default",
  spacing: 0,
  orientation: "horizontal",
  type: "single",
});

const modelValue = defineModel<string | string[]>();

provide("toggle-group", {
  get variant() { return props.variant; },
  get size() { return props.size; },
  get spacing() { return props.spacing; },
  get type() { return props.type; },
  modelValue,
  toggle: (value: string) => {
    if (props.type === "multiple") {
      const current = (modelValue.value as string[]) ?? [];
      modelValue.value = current.includes(value)
        ? current.filter((v) => v !== value)
        : [...current, value];
    } else {
      modelValue.value = modelValue.value === value ? "" : value;
    }
  },
});
</script>

<template>
  <div
    data-slot="toggle-group"
    :data-variant="props.variant"
    :data-size="props.size"
    :data-spacing="props.spacing"
    :data-orientation="props.orientation"
    :class="styles.root"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/toggle-group/toggle-group.tsx
import React from "react";
import { Toggle as ToggleBase } from "@base-ui/react/toggle";
import { ToggleGroup as ToggleGroupBase } from "@base-ui/react/toggle-group";
import * as styles from "@openlab-ui/core/toggle-group/toggle-group.css";
import * as toggleStyles from "@openlab-ui/core/toggle/toggle.css";
import type { ToggleVariants } from "@openlab-ui/core/toggle/toggle.css";

const ToggleGroupContext = React.createContext<
  ToggleVariants & { spacing?: number; orientation?: "horizontal" | "vertical" }
>({
  size: "default",
  variant: "default",
  spacing: 0,
  orientation: "horizontal",
});

export function ToggleGroup({
  variant,
  size,
  spacing = 0,
  orientation = "horizontal",
  children,
  ...props
}: ToggleGroupBase.Props &
  ToggleVariants & {
    spacing?: number;
    orientation?: "horizontal" | "vertical";
  }) {
  return (
    <ToggleGroupBase
      data-slot="toggle-group"
      data-variant={variant}
      data-size={size}
      data-spacing={spacing}
      data-orientation={orientation}
      className={styles.root}
      {...props}
    >
      <ToggleGroupContext.Provider
        value={{ variant, size, spacing, orientation }}
      >
        {children}
      </ToggleGroupContext.Provider>
    </ToggleGroupBase>
  );
}

export function ToggleGroupItem({
  variant = "default",
  size = "default",
  ...props
}: ToggleBase.Props & ToggleVariants) {
  const ctx = React.useContext(ToggleGroupContext);
  return (
    <ToggleBase
      data-slot="toggle-group-item"
      data-variant={ctx.variant ?? variant}
      data-size={ctx.size ?? size}
      data-spacing={ctx.spacing}
      className={[
        toggleStyles.toggle({
          variant: ctx.variant ?? variant,
          size: ctx.size ?? size,
        }),
        styles.item,
      ].join(" ")}
      {...props}
    />
  );
}
