// packages/react/src/components/button/button.tsx
import { Button as BaseButton } from "@base-ui/react/button";
import type { ButtonVariants } from "@openlab-ui/core/button/button.css";
import * as styles from "@openlab-ui/core/button/button.css";

export type ButtonProps = React.ComponentProps<typeof BaseButton> &
  ButtonVariants;

export function Button({ variant, size, className, ...props }: ButtonProps) {
  return (
    <BaseButton
      data-slot="button"
      className={styles.button({ variant, size })}
      {...props}
    />
  );
}
Button.displayName = "OpenLabUIButton";

export { styles as buttonStyles };
export type { ButtonVariants };

// packages/vue/src/components/button/Button.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/button/button.css";
import { Button } from "base-ui-vue";
import { computed } from "vue";

type ButtonProps = {
    variant?:
        | "default"
        | "outline"
        | "secondary"
        | "ghost"
        | "destructive"
        | "link";
    size?:
        | "default"
        | "xs"
        | "sm"
        | "lg"
        | "icon"
        | "icon-xs"
        | "icon-sm"
        | "icon-lg";
};

const props = defineProps<ButtonProps>();
const className = computed(() =>
    styles.button({ variant: props.variant, size: props.size }),
);
</script>

<template>
    <Button :class="className">
        <slot></slot>
    </Button>
</template>
