// examples/docs/src/components/previews/vue/BadgePreview.vue
<script setup lang="ts">
import { Badge } from "@openlab-ui/vue";
import VuePreviewProvider from "../../VuePreviewProvider.vue";
</script>

<template>
  <VuePreviewProvider>
    <Badge variant="default">Default</Badge>
    <Badge variant="secondary">Secondary</Badge>
    <Badge variant="outline">Outline</Badge>
    <Badge variant="destructive">Destructive</Badge>
  </VuePreviewProvider>
</template>

// examples/docs/src/components/previews/react/BadgePreview.tsx
import { Badge } from "@openlab-ui/react";
import { ReactPreviewProvider } from "../../ReactPreviewProvider";

export function BadgeVariants() {
  return (
    <ReactPreviewProvider>
      <Badge variant="default">Default</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="outline">Outline</Badge>
      <Badge variant="destructive">Destructive</Badge>
    </ReactPreviewProvider>
  );
}
