// examples/docs/src/components/previews/vue/CheckboxPreview.vue
<script setup lang="ts">
import { Checkbox, Label, Field } from "@openlab-ui/vue";
import VuePreviewProvider from "../../VuePreviewProvider.vue";
</script>

<template>
  <VuePreviewProvider>
    <div style="display: flex; flex-direction: column; gap: 0.75rem">
      <Field orientation="horizontal">
        <Checkbox id="terms-vue" :default-checked="true" />
        <Label for="terms-vue">Accept terms and conditions</Label>
      </Field>
      <Field orientation="horizontal">
        <Checkbox id="newsletter-vue" />
        <Label for="newsletter-vue">Subscribe to newsletter</Label>
      </Field>
      <Field orientation="horizontal">
        <Checkbox id="disabled-vue" :disabled="true" />
        <Label for="disabled-vue">Disabled option</Label>
      </Field>
    </div>
  </VuePreviewProvider>
</template>

// examples/docs/src/components/previews/react/CheckboxPreview.tsx
import { Checkbox, Label, Field } from "@openlab-ui/react";
import { ReactPreviewProvider } from "../../ReactPreviewProvider";

export function CheckboxBasic() {
  return (
    <ReactPreviewProvider>
      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
        <Field orientation="horizontal">
          <Checkbox id="terms" defaultChecked />
          <Label htmlFor="terms">Accept terms and conditions</Label>
        </Field>
        <Field orientation="horizontal">
          <Checkbox id="newsletter" />
          <Label htmlFor="newsletter">Subscribe to newsletter</Label>
        </Field>
        <Field orientation="horizontal">
          <Checkbox id="disabled" disabled />
          <Label htmlFor="disabled">Disabled option</Label>
        </Field>
      </div>
    </ReactPreviewProvider>
  );
}
