// examples/docs/src/components/previews/vue/NumberFieldPreview.vue
<script setup lang="ts">
import {
  NumberFieldRoot,
  NumberFieldGroup,
  NumberFieldInput,
  NumberFieldIncrement,
  NumberFieldDecrement,
  Label,
  Field,
} from "@openlab-ui/vue";
import VuePreviewProvider from "../../VuePreviewProvider.vue";
</script>

<template>
  <VuePreviewProvider>
    <div style="display: flex; flex-direction: column; gap: 1rem; width: 100%; max-width: 280px">
      <Field>
        <Label>Quantity</Label>
        <NumberFieldRoot :default-value="1" :min="0" :max="99">
          <NumberFieldGroup>
            <NumberFieldDecrement>−</NumberFieldDecrement>
            <NumberFieldInput />
            <NumberFieldIncrement>+</NumberFieldIncrement>
          </NumberFieldGroup>
        </NumberFieldRoot>
      </Field>
      <Field>
        <Label>Price (disabled)</Label>
        <NumberFieldRoot :default-value="42" :disabled="true">
          <NumberFieldGroup>
            <NumberFieldDecrement>−</NumberFieldDecrement>
            <NumberFieldInput />
            <NumberFieldIncrement>+</NumberFieldIncrement>
          </NumberFieldGroup>
        </NumberFieldRoot>
      </Field>
    </div>
  </VuePreviewProvider>
</template>

// examples/docs/src/components/previews/react/NumberFieldPreview.tsx
import { NumberField, Label, Field } from "@openlab-ui/react";
import { ReactPreviewProvider } from "../../ReactPreviewProvider";

export function NumberFieldBasic() {
  return (
    <ReactPreviewProvider>
      <div style={{ display: "flex", flexDirection: "column", gap: "1rem", width: "100%", maxWidth: 280 }}>
        <Field>
          <Label>Quantity</Label>
          <NumberField.Root defaultValue={1} min={0} max={99}>
            <NumberField.Group>
              <NumberField.Decrement>−</NumberField.Decrement>
              <NumberField.Input />
              <NumberField.Increment>+</NumberField.Increment>
            </NumberField.Group>
          </NumberField.Root>
        </Field>
        <Field>
          <Label>Price (disabled)</Label>
          <NumberField.Root defaultValue={42} disabled>
            <NumberField.Group>
              <NumberField.Decrement>−</NumberField.Decrement>
              <NumberField.Input />
              <NumberField.Increment>+</NumberField.Increment>
            </NumberField.Group>
          </NumberField.Root>
        </Field>
      </div>
    </ReactPreviewProvider>
  );
}
