// examples/docs/src/components/previews/vue/ToastPreview.vue
<script setup lang="ts">
import { Button } from "@openlab-ui/vue";
import VuePreviewProvider from "../../VuePreviewProvider.vue";
</script>

<template>
  <VuePreviewProvider>
    <div style="display: flex; flex-direction: column; gap: 0.75rem; align-items: flex-start">
      <p style="font-size: 0.875rem; color: var(--color-muted-foreground)">
        Toast notifications can be integrated with any toast library.
      </p>
      <Button variant="outline">Show Toast</Button>
    </div>
  </VuePreviewProvider>
</template>

// examples/docs/src/components/previews/react/ToastPreview.tsx
import { Button } from "@openlab-ui/react";
import { ReactPreviewProvider } from "../../ReactPreviewProvider";

export function ToastBasic() {
  return (
    <ReactPreviewProvider>
      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem", alignItems: "flex-start" }}>
        <p style={{ fontSize: "0.875rem", color: "var(--color-muted-foreground)" }}>
          Toast notifications require the <code>sonner</code> package. Install it and wrap
          your app with the <code>Toaster</code> component.
        </p>
        <Button variant="outline" onClick={() => alert("Add sonner to your project to see toasts in action.")}>
          Show Toast
        </Button>
      </div>
    </ReactPreviewProvider>
  );
}
