// examples/docs/src/components/previews/vue/TooltipPreview.vue
<script setup lang="ts">
import { Tooltip, TooltipTrigger, TooltipContent, Button } from "@openlab-ui/vue";
import VuePreviewProvider from "../../VuePreviewProvider.vue";
</script>

<template>
  <VuePreviewProvider>
    <Tooltip>
      <TooltipTrigger as-child>
        <Button variant="outline">Hover me</Button>
      </TooltipTrigger>
      <TooltipContent>
        <p>This is a tooltip</p>
      </TooltipContent>
    </Tooltip>
    <Tooltip>
      <TooltipTrigger as-child>
        <Button variant="outline" size="sm">Top</Button>
      </TooltipTrigger>
      <TooltipContent side="top">
        <p>Appears on top</p>
      </TooltipContent>
    </Tooltip>
  </VuePreviewProvider>
</template>

// examples/docs/src/components/previews/react/TooltipPreview.tsx
import { Tooltip, TooltipTrigger, TooltipContent, Button } from "@openlab-ui/react";
import { ReactPreviewProvider } from "../../ReactPreviewProvider";

export function TooltipBasic() {
  return (
    <ReactPreviewProvider>
      <Tooltip>
        <TooltipTrigger render={<Button variant="outline">Hover me</Button>} />
        <TooltipContent><p>This is a tooltip</p></TooltipContent>
      </Tooltip>
      <Tooltip>
        <TooltipTrigger render={<Button variant="outline" size="sm">Top</Button>} />
        <TooltipContent side="top"><p>Appears on top</p></TooltipContent>
      </Tooltip>
      <Tooltip>
        <TooltipTrigger render={<Button variant="outline" size="sm">Right</Button>} />
        <TooltipContent side="right"><p>Appears on right</p></TooltipContent>
      </Tooltip>
    </ReactPreviewProvider>
  );
}
