// packages/react/src/components/slider/slider.tsx
import { Slider as SliderBase } from "@base-ui/react/slider";
import * as styles from "@openlab-ui/core/slider/slider.css";

export type SliderProps = SliderBase.Root.Props;

export function Slider({
  defaultValue,
  value,
  min = 0,
  max = 100,
  ...props
}: SliderProps) {
  const _values = Array.isArray(value)
    ? value
    : Array.isArray(defaultValue)
      ? defaultValue
      : [min, max];

  return (
    <SliderBase.Root
      data-slot="slider"
      className={styles.root}
      defaultValue={defaultValue}
      value={value}
      min={min}
      max={max}
      thumbAlignment="edge"
      {...props}
    >
      <SliderBase.Control className={styles.control}>
        <SliderBase.Track data-slot="slider-track" className={styles.track}>
          <SliderBase.Indicator
            data-slot="slider-range"
            className={styles.indicator}
          />
        </SliderBase.Track>
        {Array.from({ length: _values.length }, (_, i) => (
          <SliderBase.Thumb
            key={i}
            data-slot="slider-thumb"
            className={styles.thumb}
          />
        ))}
      </SliderBase.Control>
    </SliderBase.Root>
  );
}
Slider.displayName = "OpenLabUISlider";

// packages/vue/src/components/slider/Slider.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/slider/slider.css";
import { computed } from "vue";

interface Props {
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  defaultValue?: number;
}

const props = withDefaults(defineProps<Props>(), { min: 0, max: 100, step: 1 });

const model = defineModel<number>({ default: 0 });

const percentage = computed(() => {
  const val = model.value ?? props.defaultValue ?? props.min;
  return ((val - props.min) / (props.max - props.min)) * 100;
});
</script>

<template>
  <div data-slot="slider" data-orientation="horizontal" :class="styles.root">
    <div :class="styles.control" data-orientation="horizontal">
      <div data-slot="slider-track" :class="styles.track" data-orientation="horizontal">
        <div
          data-slot="slider-range"
          :class="styles.indicator"
          data-orientation="horizontal"
          :style="`width: ${percentage}%`"
        />
      </div>
      <span
        data-slot="slider-thumb"
        :class="styles.thumb"
        :style="`position: absolute; left: calc(${percentage}% - 0.5rem); top: 50%; transform: translateY(-50%)`"
      />
      <input
        type="range"
        :min="props.min"
        :max="props.max"
        :step="props.step"
        :disabled="props.disabled"
        :value="model"
        aria-hidden="true"
        style="position: absolute; inset: 0; opacity: 0; cursor: pointer; width: 100%"
        @input="model = Number(($event.target as HTMLInputElement).value)"
      />
    </div>
  </div>
</template>
