// packages/vue/src/components/separator/Separator.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/separator/separator.css";

interface Props {
  orientation?: "horizontal" | "vertical";
}

withDefaults(defineProps<Props>(), { orientation: "horizontal" });
</script>

<template>
  <div
    role="separator"
    :class="styles.root"
  />
</template>

// packages/react/src/components/separator/separator.tsx
import {
  Separator as SeparatorBase,
  type SeparatorProps,
} from "@base-ui/react/separator";
import * as styles from "@openlab-ui/core/separator/separator.css";

export type { SeparatorProps };

export function Separator(props: SeparatorProps) {
  return <SeparatorBase className={styles.root} {...props} />;
}
Separator.displayName = "OpenLabUISeparator";
