// packages/vue/src/components/badge/Badge.vue
<script setup lang="ts">
import * as styles from "@openlab-ui/core/badge/badge.css";

interface Props {
  variant?: "default" | "secondary" | "destructive" | "outline" | "ghost" | "link";
}

const props = withDefaults(defineProps<Props>(), { variant: "default" });
</script>

<template>
  <span data-slot="badge" :class="styles.badge({ variant: props.variant })">
    <slot />
  </span>
</template>

// packages/react/src/components/badge/badge.tsx
import * as styles from "@openlab-ui/core/badge/badge.css";
import type { BadgeVariants } from "@openlab-ui/core/badge/badge.css";

export type { BadgeVariants };

export function Badge({
  variant = "default",
  ...props
}: React.ComponentProps<"span"> & BadgeVariants) {
  return (
    <span data-slot="badge" className={styles.badge({ variant })} {...props} />
  );
}
